# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c262a61e652737785fa3a9f66d877ed2cc78a9cd376ab72f809fd84b7a3f1aee84d8496f495bdac3ea6af31a630dae9bbef61ab327996f247abbb2aeed05be08

test:
  secret_key_base: d2c24158ed51f905eb10177b3ea2c5fa5c8c7de96ba49a92eea30f13d206ece8ea0ba22c4074d87334a1fe5be3f964a7cd81d13f15eb0dcaab62f9e4f8ca6883

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
